Upgrading cargo dependency of mpl-token-metadata.
Calyptus-Learn/solana-nft-anchor pull request #2
Opened 2023-11-04 12:59 UTC by rosarp

With mpl-token-metadata upgraded, there are minor API changes which mandates code changes to accommodate upgrade.

2023-12-05 09:38 UTC, Gungz commented
Seems like I agree with this pull request, in my case, I keep using version 0.28.0 of anchor-lang and anchor-spl to avoid error. So, the way to finish the tutorial should be upgrading cargo dependency or the tutorial has to be updated to restrict version of anchor-lang and spl to 0.28.0.

2023-12-06 06:24 UTC, dishui78157 reviewed
LGTM. Thanks for the commit

2024-01-22 09:53 UTC, jim4067 requested changes

2024-01-22 09:53 UTC, jim4067 commented on programs/solana-nft-anchor/Cargo.toml
> +mpl-token-metadata = "3.2.0"
```suggestion
mpl-token-metadata = "4.0.0"
```

2024-01-22 09:53 UTC, jim4067 commented on programs/solana-nft-anchor/src/lib.rs
> +    types::DataV2,
```suggestion
```

2024-01-22 09:56 UTC, jim4067 commented on programs/solana-nft-anchor/src/lib.rs
> +    types::DataV2,
@rosarp, for the removed `types::DataV2,`, could you reimport it from the `anchor_spl` module 

i.e 

```rs
use anchor_spl::{
    metadata::{
        mpl_token_metadata::types::DataV2, // import it here instead
    },
};
```

2024-01-22 10:48 UTC, jim4067 commented
Thank you for this 👍🏾

2024-01-22 10:48 UTC, merged